### PR TITLE
Improve intellisense support #58

### PR DESCRIPTION
**Pull request by lorenzocelli**
Now intellisense should understand the type of `my_function.schema` and as a consequence also suggest arguments for add_enum.

The annotation (unfortunately a little verbose) should have done the trick:
```python
def GPTEnabled(
    func: Callable = None, **kwargs
) -> Union[_GPTEnabled, Callable[[Callable], _GPTEnabled]]:
```

I also removed the quotas from the return annotation in `add_enum` by importing future annotations and added `return` to the docstring. 

@siliconlad let me know if it works on your end as well :)

### CODE REVIEW

**Comment by lorenzocelli** [comment]
With the latest changes the hover tooltip is a bit confused:
Screenshot 2024-03-29 at 18 22 32
But the docstring and the arguments appear when typing in between parenthesis:
Screenshot 2024-03-29 at 18 21 58
The return value type also appears:
Screenshot 2024-03-29 at 18 22 17

Unfortunately, ParamSpec is not supported in Python 3.9

**Comment by siliconlad** [comment]
There is no intellisense with the following code as well (unless th:

```python
def FindGPTEnabledSchemas(
    module: ModuleType, schema_type: SchemaType = SchemaType.API
) -> list[dict]:
    """
    Find all function schemas with the GPTEnabled decorator.

    :param module: Module to search for GPTEnabled functions
    :param schema_type: Type of schema to return
    """
    return [x.schema.to_json(schema_type) for x in FindGPTEnabled(module)]
```

Would it be better to bite the bullet and just completely change the type (e.g. `Tool`) and then have that inherit from `Callable` (is that necessary?). Would provide a clearer interface, at the expense of losing your function "type".

**Comment by lorenzocelli** [comment]
> Would it be better to bite the bullet and just completely change the type (e.g. Tool) and then have that inherit from Callable (is that necessary?). Would provide a clearer interface, at the expense of losing your function "type".

I am not sure I unterstand. Do you mean have `_GPTEnabled` inherit from callable?

**Comment by siliconlad** [comment]
LGTM!

**Pull request merged**
