### PR TITLE
Add coverage to workflow #51

### PR DESCRIPTION
**Pull request by lorenzocelli**
Add coverage report using 
- [irongut/CodeCoverageSummary](https://github.com/marketplace/actions/code-coverage-summary)
- [marocchino/sticky-pull-request-comment](https://github.com/marocchino/sticky-pull-request-comment)

### CODE REVIEW

**Comment by lorenzocelli** [comment]
With this action it is currently not possible to include the badge in the readme (the author mentions it in [this issue](https://github.com/irongut/CodeCoverageSummary/issues/34)).

@siliconlad do we want the coverage to fail under a certain threshold?

**Comment by siliconlad** [comment]
> With this action it is currently not possible to include the badge in the readme (the author mentions it in [this issue](https://github.com/irongut/CodeCoverageSummary/issues/34)).

Is it silly to get the bot to overwrite the badge in the README every time (or on merge)?

**Comment by siliconlad** [comment]
> @siliconlad do we want the coverage to fail under a certain threshold?

Is there a reason not to set it at 100%?

**Comment by lorenzocelli** [comment]
> Is there a reason not to set it at 100%?

I don't see any. I will have it fail then

**Comment by lorenzocelli** [comment]
> Is it silly to get the bot to overwrite the badge in the README every time (or on merge)?

I don't think it is worth the effort, but if we really want the badge we can do it

**Comment by siliconlad** [comment]
> > Is it silly to get the bot to overwrite the badge in the README every time (or on merge)?
> 
> I don't think it is worth the effort, but if we really want the badge we can do it

Let's leave it then 👍

**Comment by siliconlad** [comment]
Do we need the bot vs just a job that fails? I wonder how annoying the bot will become.

**Comment by lorenzocelli** [comment]
Let's get rid of the bot 🤖🔫

**Comment by lorenzocelli** [comment]
The non-tested code we have is the following. In `parameter_schema.py`:

```python
class ParameterSchema:

    @staticmethod
    def matches(parameter: Parameter) -> bool:
        raise NotImplementedError()  # <---- this line

    def _get_type(self) -> Union[str, Parameter.empty]:
        return Parameter.empty  # <---- this line
```
Maybe it can be solved with [abstract classes](https://docs.python.org/3/library/abc.html).
In `schema.py`:

```python
# ---- this method ----
def SaveGPTEnabled(module: ModuleType, path: str, schema_type: SchemaType = SchemaType.API):
    schemas = FindGPTEnabledSchemas(module, schema_type)
    json.dump(schemas, open(path, "w"))

# ...

class _GPTEnabled:
    # ...

    # ---- this method ----
    def gpt_enabled(self) -> bool:
        return True

# ...

class FunctionSchema:

    # ...

    def _get_parameters_schema(self, schema_type: SchemaType) -> dict:
        schema = {"type": "object"}
        
        if not self.parameter_schemas and schema_type == SchemaType.API:
            # Skip properties
            return schema  # <---- this line
```

**Comment by siliconlad** [comment]
Lowered the threshold to 95%.

**Pull request merged**
